### ISSUE TITLE
[Suggestions] DOI http link, and author/year on node

### ISSUE THREAD

**Issue by chiptuned** [aMarcireau/origami#1]
Hi,
Is it possible to add a DOI with its http link attached (with the "https://doi.org/" prefix)?
Also, it would be more convenient for me to visualise nodes with the first letters of the author and the year (the 2 last digits), for instance "Go99" for a 1999 paper from Tim Gollish, and so on.
Thanks

**Comment by aMarcireau** [comment]
I like both ideas!
