### ISSUE TITLE
[Suggestion] Add release info

### ISSUE THREAD

**Issue by chiptuned** [aMarcireau/origami#21]
It would be great to have the release name at least somewhere in the app.

**Comment by aMarcireau** [comment]
By release name, do you mean the version?

**Comment by chiptuned** [comment]
Yes

**Comment by aMarcireau** [comment]
This feature, though quite relevant right now (fast changing, non-retro-compatible versions), will not be in the future. The following workaround is recommended:
- macOS: in the app, click on *Origami > About Origami*
- Linux and Windows: in the file browser, open *Origami/resources/app/package.json*
